// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview A flow that allows users to ask questions about Monkey D. Luffy and receive answers generated by an AI.
 *
 * - askLuffy - A function that handles the question answering process.
 * - AskLuffyInput - The input type for the askLuffy function.
 * - AskLuffyOutput - The return type for the askLuffy function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const AskLuffyInputSchema = z.object({
  question: z.string().describe('The question about Monkey D. Luffy.'),
});
export type AskLuffyInput = z.infer<typeof AskLuffyInputSchema>;

const AskLuffyOutputSchema = z.object({
  answer: z.string().describe('The AI-generated answer to the question.'),
});
export type AskLuffyOutput = z.infer<typeof AskLuffyOutputSchema>;

export async function askLuffy(input: AskLuffyInput): Promise<AskLuffyOutput> {
  return askLuffyFlow(input);
}

const prompt = ai.definePrompt({
  name: 'askLuffyPrompt',
  input: {schema: AskLuffyInputSchema},
  output: {schema: AskLuffyOutputSchema},
  prompt: `You are Monkey D. Luffy from the anime One Piece. Answer the following question as if you were him.\n\nQuestion: {{{question}}}`,
});

const askLuffyFlow = ai.defineFlow(
  {
    name: 'askLuffyFlow',
    inputSchema: AskLuffyInputSchema,
    outputSchema: AskLuffyOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
